"""Public Python API: :class:`Fakeverse` and :class:`UniverseGenerator`."""

from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from fakeverse import __version__
from fakeverse.capabilities import Capabilities
from fakeverse.engine.colocate import compile_with_groups
from fakeverse.engine.explain import Node, count_fallbacks, to_output
from fakeverse.engine.generators import (
    Draw,
    LocatedGenerator,
    resolve_generator,
    resolve_located_generator,
)
from fakeverse.engine.index import UniverseIndex, build_index
from fakeverse.engine.revision import ENGINE_REVISION
from fakeverse.engine.template import DEFAULT_MAX_LEAVES, render_row
from fakeverse.engine.unique import Items, generate_items, uniqueness
from fakeverse.errors import InvalidOption, LocaleNotSupported, UniverseNotFound
from fakeverse.loader import embedded_universes_dir, load_directory
from fakeverse.locale import LocalizedValue, is_locale_supported, normalize_locale, resolve
from fakeverse.rng import MAX_SEED, Rng, derive_seed, random_seed


@dataclass(frozen=True, slots=True)
class UniverseInfo:
    """Summary of a universe."""

    id: str
    name: str
    """Name in the requested locale (default locale of the universe otherwise)."""
    locales: tuple[str, ...]
    default_locale: str


@dataclass(frozen=True, slots=True)
class GenerationMeta:
    """Metadata of a generation."""

    universe: str
    type: str
    """The generated type, or ``template``."""
    count: int
    seed: int
    seed_generated: bool
    """Whether the seed was drawn because none was given."""
    locale: str
    locale_fallbacks: int
    """Number of values that fell back to another language."""
    data_version: str
    engine_revision: int
    duplicates: int = 0
    """Number of items equal to a previous one (the pool was too small, or ``unique=False``)."""

    def to_dict(self) -> dict[str, Any]:
        """Return the metadata as a JSON-serializable mapping."""
        return asdict(self)


@dataclass(frozen=True, slots=True)
class GenerationResult:
    """Items generated by a request, with their metadata."""

    items: list[Any]
    """Raw values (scalars for atomic types, objects otherwise), or explain objects."""
    meta: GenerationMeta


class Fakeverse:
    """Entry point: loads and validates universes once, then hands out generators.

    Args:
        universes_dir: directory of universe files; the embedded universes by default.
        data_version: version of these data, reported in results; the package version by
            default (the package always uses its own data). The API sets it for each of
            its data snapshots.

    Raises:
        UniverseValidationError: with the complete list of problems if a file is invalid.
    """

    def __init__(self, universes_dir: Path | None = None, data_version: str | None = None) -> None:
        directory = universes_dir if universes_dir is not None else embedded_universes_dir()
        universes = load_directory(directory) if directory.is_dir() else {}
        self._indexes: dict[str, UniverseIndex] = {
            universe_id: build_index(universe) for universe_id, universe in universes.items()
        }
        self._data_version = data_version if data_version is not None else __version__

    @property
    def data_version(self) -> str:
        """Version of the data."""
        return self._data_version

    def universes(self, locale: str | None = None) -> list[UniverseInfo]:
        """List the available universes, with names in ``locale`` when given."""
        infos = []
        for index in self._indexes.values():
            meta = index.universe.universe
            wanted = _normalize(locale) if locale is not None else meta.default_locale
            infos.append(
                UniverseInfo(
                    id=meta.id,
                    name=resolve(meta.name, wanted, meta.default_locale).value,
                    locales=tuple(meta.locales),
                    default_locale=meta.default_locale,
                )
            )
        return infos

    def universe(self, universe_id: str, locale: str | None = None) -> UniverseGenerator:
        """Return a generator bound to a universe and a locale.

        Args:
            universe_id: identifier of the universe.
            locale: BCP-47 locale (``fr``, ``fr_FR``...); the default locale of the universe
                when omitted.

        Raises:
            UniverseNotFound: if the universe does not exist.
            LocaleNotSupported: if the language of ``locale`` is not supported.
            InvalidOption: if ``locale`` is malformed.
        """
        index = self._indexes.get(universe_id)
        if index is None:
            known = ", ".join(self._indexes) or "none"
            raise UniverseNotFound(f"Unknown universe '{universe_id}'. Available: {known}.")
        meta = index.universe.universe
        resolved = meta.default_locale if locale is None else _normalize(locale)
        if not is_locale_supported(resolved, meta.locales):
            raise LocaleNotSupported(
                f"Universe '{universe_id}' does not support locale '{resolved}'. "
                f"Supported: {', '.join(meta.locales)}."
            )
        return UniverseGenerator(index, resolved, self.data_version)


def _normalize(locale: str) -> str:
    try:
        return normalize_locale(locale)
    except ValueError as exc:
        raise InvalidOption(str(exc)) from exc


class UniverseGenerator:
    """Generates data of one universe in one locale."""

    def __init__(self, index: UniverseIndex, locale: str, data_version: str) -> None:
        self._index = index
        self.locale = locale
        """Normalized locale of the generator."""
        self.data_version = data_version

    @property
    def id(self) -> str:
        """Identifier of the universe."""
        return self._index.id

    @property
    def index(self) -> UniverseIndex:
        """Compiled universe (engine internals, for tooling such as coherence checks)."""
        return self._index

    def label(self, value: LocalizedValue) -> str:
        """Resolve a localized label (universe name, extension label...) in this locale."""
        return resolve(value, self.locale, self._index.default_locale).value

    def capabilities(self) -> Capabilities:
        """Types supported by the universe."""
        return self._index.capabilities

    def generate(
        self,
        type_id: str,
        count: int = 1,
        seed: int | None = None,
        *,
        unique: bool | None = None,
        explain: bool = False,
        gender: str | None = None,
        people: str | None = None,
    ) -> GenerationResult:
        """Generate ``count`` items of a core or extension type.

        Args:
            type_id: ``person``, ``first_name``, an extension id...
            count: number of items, at least 1.
            seed: 0 to 2^63 - 1; drawn at random (and returned in ``meta``) when omitted.
            unique: ``None`` (default) avoids duplicates as long as the pool allows it and
                counts them in ``meta.duplicates`` afterwards; ``True`` raises
                ``PoolExhausted`` instead; ``False`` allows duplicates.
            explain: replace each leaf value by ``{value, origin, locale, fallback}``.
            gender: ``masculine``, ``feminine`` or ``neutral``; person types only.
            people: id of a people; person types only.

        Raises:
            TypeNotSupported, InvalidOption, PoolExhausted.
        """
        _check_count(count)
        generator = resolve_generator(self._index, type_id, gender=gender, people=people)
        options: dict[str, object] = {}
        if gender is not None:
            options["gender"] = gender
        if people is not None:
            options["people"] = people
        mode = uniqueness(unique)
        if mode == "off":
            options["unique"] = False
        seed, seed_generated = _seed(seed)

        def make(item: int, attempt: int | None) -> Node:
            return generator(self._draw(type_id, options, seed, item, attempt))

        items = generate_items(count, make, mode)
        return self._result(type_id, items, seed, seed_generated, explain)

    def one(
        self,
        type_id: str,
        seed: int | None = None,
        *,
        explain: bool = False,
        gender: str | None = None,
        people: str | None = None,
    ) -> Any:
        """Generate a single value of a type (shortcut for ``generate(...).items[0]``)."""
        result = self.generate(type_id, 1, seed, explain=explain, gender=gender, people=people)
        return result.items[0]

    def template(
        self,
        template: Mapping[str, Any],
        count: int = 1,
        seed: int | None = None,
        *,
        unique: bool | None = None,
        explain: bool = False,
        max_leaves: int = DEFAULT_MAX_LEAVES,
        colocate: Sequence[Sequence[str]] = (),
    ) -> GenerationResult:
        """Generate rows shaped by a template.

        Args:
            unique: as for :meth:`generate`, applied to whole rows.
            colocate: groups of instances that share one locality, for instance
                ``[["person", "organization"]]`` for a person working in an organization of
                their town.

        Raises:
            InvalidTemplate: with every faulty path or group at once, before any generation.
            InvalidOption, PoolExhausted.
        """
        _check_count(count)
        compiled, groups = compile_with_groups(
            template, colocate, self._index, max_leaves=max_leaves
        )
        located = {instance: group for group in groups for instance in group.instances}
        generators: dict[tuple[str, int], Callable[[Draw], Node]] = {
            instance: resolve_generator(self._index, instance[0])
            for instance in compiled.instances
            if instance not in located
        }
        located_generators: dict[tuple[str, int], LocatedGenerator] = {
            instance: resolve_located_generator(self._index, instance[0]) for instance in located
        }
        mode = uniqueness(unique)
        options: dict[str, object] = {"unique": False} if mode == "off" else {}
        seed, seed_generated = _seed(seed)

        def make(row: int, attempt: int | None) -> Node:
            localities = {
                group: group.localities.draw(
                    self._draw(group.kind, options, seed, row, attempt).rng
                )
                for group in groups
            }
            instances: dict[tuple[str, int], Node] = {}
            for instance in compiled.instances:
                draw = self._draw(compiled.instance_kind(instance), options, seed, row, attempt)
                if instance in located:
                    locality = localities[located[instance]]
                    instances[instance] = located_generators[instance](draw, locality)
                else:
                    instances[instance] = generators[instance](draw)
            return render_row(compiled.structure, instances)

        rows = generate_items(count, make, mode)
        return self._result("template", rows, seed, seed_generated, explain)

    def _draw(
        self, kind: str, options: dict[str, object], seed: int, item: int, attempt: int | None
    ) -> Draw:
        components: list[object] = [ENGINE_REVISION, self.id, kind, self.locale, options, seed]
        components.append(item)
        if attempt is not None:
            components.append(attempt)
        return Draw(self._index, Rng(derive_seed(*components)), self.locale)

    def _result(
        self, type_id: str, items: Items, seed: int, seed_generated: bool, explain: bool
    ) -> GenerationResult:
        nodes = items.nodes
        meta = GenerationMeta(
            universe=self.id,
            type=type_id,
            count=len(nodes),
            seed=seed,
            seed_generated=seed_generated,
            locale=self.locale,
            locale_fallbacks=sum(count_fallbacks(node) for node in nodes),
            data_version=self.data_version,
            engine_revision=ENGINE_REVISION,
            duplicates=items.duplicates,
        )
        return GenerationResult([to_output(node, explain=explain) for node in nodes], meta)


def _check_count(count: int) -> None:
    if type(count) is not int or count < 1:
        raise InvalidOption(f"Invalid count {count!r}; expected an integer of at least 1.")


def _seed(seed: int | None) -> tuple[int, bool]:
    if seed is None:
        return random_seed(), True
    if type(seed) is not int or not 0 <= seed <= MAX_SEED:
        raise InvalidOption(f"Invalid seed {seed!r}; expected an integer from 0 to 2^63 - 1.")
    return seed, False
