"""Models of a universe file.

These models are the source of truth of the format; ``schema/universe.schema.json`` is
generated from them. They check the structure of a file; the semantic rules (references,
hierarchy, locales, patterns...) live in :mod:`fakeverse.validation`.
"""

from __future__ import annotations

import re
from typing import Annotated, Any, Final, Literal

from pydantic import Field, field_validator, model_validator
from pydantic_core import PydanticCustomError

from fakeverse.model.base import (
    FamilyNameItem,
    FieldValue,
    FirstNameItem,
    GitHubHandle,
    Id,
    Localized,
    Model,
    SnakeName,
    VocabItem,
    Weight,
)
from fakeverse.patterns.parser import MAX_INT
from fakeverse.types import PlaceLevel

FORMAT_VERSION: Final[int] = 1
RATIO_STEPS: Final[int] = 20
RATIO_TOLERANCE: Final[float] = 1e-9

_INT_RANGE = re.compile(r"^(\d+)-(\d+)$")


class Sources(Model):
    """Scope of the sources of the universe."""

    scope: Annotated[str, Field(min_length=1)]
    """Scope of the sources, in English (e.g. which books or films are covered)."""
    translations: dict[str, Annotated[str, Field(min_length=1)]] = Field(default_factory=dict)
    """Reference translation for each locale."""


class UniverseMeta(Model):
    """Identity and languages of the universe."""

    id: Id
    """Identifier, equal to the file name."""
    name: Localized
    default_locale: str
    """Fallback locale, in canonical BCP-47 form (e.g. `en`)."""
    locales: Annotated[list[str], Field(min_length=1)]
    """Supported locales; must contain `default_locale`."""
    sources: Sources
    maintainers: Annotated[list[GitHubHandle], Field(min_length=1)]
    """GitHub handles of the maintainers of this file."""


class GenerationSettings(Model):
    """Fine-tuning of the engine for this universe."""

    organization_generated_ratio: Annotated[float, Field(ge=0, le=1)] = 0.5
    """Share of organizations generated by pattern rather than drawn from the canonical ones,
    in steps of 0.05."""

    @field_validator("organization_generated_ratio")
    @classmethod
    def _check_step(cls, value: float) -> float:
        steps = value * RATIO_STEPS
        if abs(steps - round(steps)) >= RATIO_TOLERANCE:
            raise PydanticCustomError("ratio_step", "Value must be a multiple of 0.05")
        return value

    @property
    def organization_generated_steps(self) -> int:
        """The ratio as a number of twentieths."""
        return round(self.organization_generated_ratio * RATIO_STEPS)


class PlaceLevels(Model):
    """Universe-specific labels of the core place levels."""

    area: Localized | None = None
    subdivision: Localized | None = None
    locality: Localized | None = None


class PlacePatterns(Model):
    """Patterns that a place overrides for itself and its descendants."""

    street_address: Localized | None = None
    postal_code: Localized | None = None
    address_format: Localized | None = None
    phone: Localized | None = None


class Place(Model):
    """A place of one of the three core levels."""

    id: Id
    level: PlaceLevel
    parent: Id | None = None
    """Forbidden for an area; an area for a subdivision; a subdivision or an area for a
    locality."""
    name: Localized
    weight: Weight = 1
    """Draw weight among the places of the same level."""
    canon: bool = True
    patterns: PlacePatterns | None = None


class People(Model):
    """A group carrying naming rules and homelands (race, species, culture, faction)."""

    id: Id
    name: Localized
    homelands: Annotated[list[Id], Field(min_length=1)]
    """Places of any level, each containing at least one locality."""
    weight: Weight = 1
    canon: bool = True
    name_format: Localized | None = None
    """Pattern of the full name. Default: `{first_name} {family_name}` when the people has
    family names, `{first_name}` otherwise."""
    first_names: Annotated[list[FirstNameItem], Field(min_length=1)]
    family_names: Annotated[list[FamilyNameItem], Field(min_length=1)] | None = None


class Organization(Model):
    """A company, guild, inn, order..."""

    id: Id
    name: Localized
    kind: Localized | None = None
    places: list[Id] = Field(default_factory=list)
    """Places where the organization is located; any locality when empty."""
    weight: Weight = 1
    canon: bool = True


class Patterns(Model):
    """Patterns of the universe, by name."""

    street_address: Localized | None = None
    postal_code: Localized | None = None
    address_format: Localized | None = None
    phone: Localized | None = None
    email: Localized | None = None
    username: Localized | None = None
    organization_name: Localized | None = None


class ExtensionItem(Model):
    """A canonical entity of an extension in `items` form."""

    id: Id
    name: Localized
    weight: Weight = 1
    canon: bool = True
    fields: dict[SnakeName, FieldValue] = Field(default_factory=dict)
    """Additional fields; every item of an extension declares the same keys."""


class FieldSpec(Model):
    """How to generate one field of an extension in `fields` form. Exactly one key."""

    pattern: Localized | None = None
    """Render a pattern; its context is the fields declared before this one."""
    vocab: SnakeName | None = None
    """Weighted draw in a vocabulary."""
    place: PlaceLevel | None = None
    """Name of a place of this level, weighted draw."""
    people: Literal[True] | None = None
    """Name of a people, weighted draw."""
    int_range: Annotated[str | None, Field(alias="int")] = None
    """Uniform integer, as `"MIN-MAX"`."""

    @model_validator(mode="after")
    def _check_exactly_one(self) -> FieldSpec:
        given = [
            value
            for value in (self.pattern, self.vocab, self.place, self.people, self.int_range)
            if value is not None
        ]
        if len(given) != 1:
            raise PydanticCustomError(
                "field_spec",
                "A field specification has exactly one of: pattern, vocab, place, people, int",
            )
        if self.int_range is not None:
            match = _INT_RANGE.match(self.int_range)
            if match is None or not int(match[1]) <= int(match[2]) <= MAX_INT:
                raise PydanticCustomError(
                    "int_range",
                    "Expected 'MIN-MAX' with 0 <= MIN <= MAX <= 10^9",
                )
        return self

    @property
    def bounds(self) -> tuple[int, int] | None:
        """The `(MIN, MAX)` bounds of an `int` field."""
        if self.int_range is None:
            return None
        low, high = self.int_range.split("-")
        return int(low), int(high)


class Extension(Model):
    """A type specific to the universe. Exactly one of `items` or `fields`."""

    label: Localized
    items: Annotated[list[ExtensionItem], Field(min_length=1)] | None = None
    """Draw among canonical entities."""
    fields: Annotated[dict[SnakeName, FieldSpec], Field(min_length=1)] | None = None
    """Field-by-field generation, in declaration order."""

    @model_validator(mode="after")
    def _check_exactly_one_form(self) -> Extension:
        if (self.items is None) == (self.fields is None):
            raise PydanticCustomError(
                "extension_form", "An extension defines exactly one of: items, fields"
            )
        return self


class UniverseFile(Model):
    """A universe file: `universes/<id>.yaml`."""

    format: Literal[1]
    """Version of the file format."""
    universe: UniverseMeta
    generation: GenerationSettings = GenerationSettings()
    place_levels: PlaceLevels | None = None
    places: list[Place]
    peoples: list[People]
    organizations: list[Organization] = Field(default_factory=list)
    vocab: dict[SnakeName, Annotated[list[VocabItem], Field(min_length=1)]] = Field(
        default_factory=dict
    )
    patterns: Patterns = Patterns()
    extensions: dict[Id, Extension] = Field(default_factory=dict)


def universe_json_schema() -> dict[str, Any]:
    """Return the JSON Schema of the universe file format."""
    schema = UniverseFile.model_json_schema()
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Fakeverse universe",
        **{key: value for key, value in schema.items() if key != "title"},
    }
