"""Generator of the ``organization`` core type."""

from __future__ import annotations

from fakeverse.engine.explain import NULL, Node
from fakeverse.engine.generators.address import generate_address
from fakeverse.engine.generators.common import Draw
from fakeverse.engine.index import (
    LocalityInfo,
    Pool,
    hosts,
    locality_weight,
    organization_weight,
)
from fakeverse.model.universe import RATIO_STEPS


def generate_organization(draw: Draw, locality: LocalityInfo | None = None) -> dict[str, Node]:
    """Generate an organization, canonical or generated by pattern.

    When both sources exist, the generated source is chosen with probability
    ``generation.organization_generated_ratio``, as ``below(20) < k``.

    With an imposed ``locality`` (template colocation), only the canonical organizations
    located there are candidates. The caller guarantees that one source remains.
    """
    index = draw.index
    rng = draw.rng
    canonical = index.organizations
    pattern = index.organization_name
    if locality is not None and canonical is not None:
        located = [info for info in canonical.items if hosts(info.localities, locality)]
        canonical = Pool(located, organization_weight) if located else None
    if canonical is not None and pattern is not None:
        steps = index.universe.generation.organization_generated_steps
        generated = rng.below(RATIO_STEPS) < steps
    else:
        generated = canonical is None

    if generated:
        if pattern is None:  # pragma: no cover - excluded by the capabilities
            raise ValueError("no organization_name pattern")
        towns = index.localities if locality is None else Pool([locality], locality_weight)
        address, locality, places = generate_address(draw, towns)
        name = draw.render(pattern, places)
        kind = NULL
    else:
        assert canonical is not None
        info = canonical.draw(rng)
        org = info.organization
        towns = info.localities if locality is None else Pool([locality], locality_weight)
        address, locality, places = generate_address(draw, towns)
        name = draw.text(org.name, canon=org.canon)
        kind = NULL if org.kind is None else draw.text(org.kind, canon=org.canon)
    phone = draw.render_optional(locality.phone, places)
    return {"name": name, "kind": kind, "address": address, "phone": phone}
